name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    name: Build & Upload
    runs-on: ubuntu-latest

    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-apple-darwin, x86_64-pc-windows-gnu]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust target
        run: rustup target add ${{ matrix.target }}

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }}

      - name: Package binary
        run: |
          mkdir -p dist
          BIN_NAME=$(basename $(pwd))  # assumes binary = repo name
          ARTIFACT="${BIN_NAME}-${{ matrix.target }}.tar.gz"
          cd target/${{ matrix.target }}/release
          tar -czf "../../../dist/$ARTIFACT" $BIN_NAME
          cd -

      - name: Upload artifact
        uses: softprops/action-gh-release@v1
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
