name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build -r
      
    - name: Run tests
      run: cargo test

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
          name: link_expander
          path: target/release/link_expander

    - name: Setup SSH
      run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts
    - name: copy builds to server
      run: |
          rsync -vrm  target/release/link_expander ${{ secrets.USER_IP }}:/var/www/bin/
